Ajout des organization
srosset81/classe-dehors pull request #6
Opened 2021-05-16 18:37 UTC by alexfauquette

## Les grandes lignes de modifications:

 - J'utilise la relation `pair:operatedBy` pour relier un événement (Webinaire) à une organization
 - Les organizations sont du type `pair:organizationOfMembership` Sémentiquement, c'est ce que j'ai trouvé de plus cohérent
 - Les organisations sont accessible à partir le la page `/Organization`. Mais les utilisateurs les créeront grace à un quick create dans le formulaire de `Event`.
 
## La page d'une organisation (titre, lien et description en markdown)
![image](https://user-images.githubusercontent.com/45398769/118408541-5140b480-b686-11eb-8260-a0844bcc23ae.png)

## L'interface pour créer une organisation
![image](https://user-images.githubusercontent.com/45398769/118408239-fb1f4180-b684-11eb-8ed8-aa7921785347.png)

## la liste des webinaire filtrable par organisation associée
![image](https://user-images.githubusercontent.com/45398769/118408329-6f59e500-b685-11eb-825c-ada12f372857.png)

2021-05-18 10:25 UTC, srosset81 requested changes

2021-05-18 10:25 UTC, srosset81 commented on frontend/src/resources/Organization/index.js
> +    types: ["pair:organizationOfMembership"],
Il faut utiliser la classe `pair:Organization`.
`pair:organizationOfMembership` c'est un prédicat qui permet de lier une Organization avec un Rôle (et de faire des relations réifiées, pour définir la relation d'une personne avec une organisation, p.ex. président,sSecrétaire, etc). Ce n'est donc pas une classe (si ça fonctionne c'est parce qu'on ne vérifie pas encore l'ontologie côté middleware).

2021-05-18 10:25 UTC, srosset81 commented on middleware/containers.js
> +    dereference: ['pair:hasLocation/pair:hasPostalAddress', 'pair:operatedBy']
Normalement tu n'as pas besoin de déréférencer ce type de relation. React-Admin est assez intelligent pour aller chercher les données de l'organisation à partir de l'URL.

2021-05-18 10:25 UTC, srosset81 commented on middleware/containers.js
> +    acceptedTypes: 'pair:organizationOfMembership'
pair:Organization

2021-05-18 17:34 UTC, alexfauquette commented
Ok, je suppose que les mots avec majuscule sont les classes, et ceux commençant par une minuscule sont des prédicats

J'en ai profité pour inclure les organisations dans la liste des events:

![image](https://user-images.githubusercontent.com/45398769/118697581-bf64b300-b80f-11eb-9e46-6f28206abec9.png)

2021-05-18 18:17 UTC, srosset81 approved these changes

2021-05-18 18:17 UTC, srosset81 commented on frontend/src/resources/Event/EventList.js
> +          />
Le composant DateField de react-admin est limité. Il ne marche pas bien sous Firefox. Je recommande de plutôt utiliser le composant que nous avons développé ici:
https://dev.semapps.org/docs/frontend/date-components

2021-05-19 18:13 UTC, alexfauquette commented on frontend/src/resources/Event/EventList.js
> +          />
Dans ce lien, je ne vois que des composant de type Input. Alors que la les `DateField` sont utilisé pour afficher des dates.

J'ai fait plus simple dans le commit suivant. J'ai enlevé tous les `DateField`, et j'ai mis du text formaté par `date-fns ` directement, Avec 3 types de cas : 

- L'événement qui commence et fini sur la journée s'affiche : "Le 01/01/2020 de 20:30 à 21:30"
- L'événement qui dure plusieurs jours s'affiche : "Du 01/01/2020 20:30 au 02/01/2020 09:00"
- L'événement qui avec uniquement une date de début s'affiche : "Le 01/01/2020 à 20:30"

2021-05-19 19:46 UTC, srosset81 approved these changes

2021-05-19 19:47 UTC, srosset81 commented on frontend/src/resources/Event/EventList.js
> +          />
Effectivement !
C'est du beau travail !
Dis-moi si c'est bon pour toi et je mets en prod.

2021-05-20 06:42 UTC, alexfauquette commented on frontend/src/resources/Event/EventList.js
> +          />
Oui, c'est bon pour moi :)

2021-05-20 15:14 UTC, merged